INSERT INTO positions (id, name) VALUES (1, '프런트엔드');
INSERT INTO positions (id, name) VALUES (2, '백엔드');
INSERT INTO positions (id, name) VALUES (3, '디자이너');
INSERT INTO positions (id, name) VALUES (4, 'IOS');
INSERT INTO positions (id, name) VALUES (5, '안드로이드');
INSERT INTO positions (id, name) VALUES (6, '데브옵스');
INSERT INTO positions (id, name) VALUES (7, 'PM');
INSERT INTO positions (id, name) VALUES (8, '기획자');
INSERT INTO positions (id, name) VALUES (9, '마케터');

INSERT INTO tech_stack (name) VALUES ('JavaScript');
INSERT INTO tech_stack (name) VALUES ('TypeScript');
INSERT INTO tech_stack (name) VALUES ('React');
INSERT INTO tech_stack (name) VALUES ('Vue');
INSERT INTO tech_stack (name) VALUES ('Nodejs');
INSERT INTO tech_stack (name) VALUES ('Spring');
INSERT INTO tech_stack (name) VALUES ('Java');
INSERT INTO tech_stack (name) VALUES ('Nextjs');
INSERT INTO tech_stack (name) VALUES ('Nestjs');
INSERT INTO tech_stack (name) VALUES ('Express');
INSERT INTO tech_stack (name) VALUES ('Go');
INSERT INTO tech_stack (name) VALUES ('C');
INSERT INTO tech_stack (name) VALUES ('Python');
INSERT INTO tech_stack (name) VALUES ('Django');
INSERT INTO tech_stack (name) VALUES ('Swift');
INSERT INTO tech_stack (name) VALUES ('Kotlin');
INSERT INTO tech_stack (name) VALUES ('MySQL');
INSERT INTO tech_stack (name) VALUES ('MongoDB');
INSERT INTO tech_stack (name) VALUES ('php');
INSERT INTO tech_stack (name) VALUES ('GraphQL');
INSERT INTO tech_stack (name) VALUES ('Firebase');
INSERT INTO tech_stack (name) VALUES ('ReactNative');
INSERT INTO tech_stack (name) VALUES ('Unity');
INSERT INTO tech_stack (name) VALUES ('Flutter');
INSERT INTO tech_stack (name) VALUES ('AWS');
INSERT INTO tech_stack (name) VALUES ('Kubernetes');
INSERT INTO tech_stack (name) VALUES ('Docker');
INSERT INTO tech_stack (name) VALUES ('Git');
INSERT INTO tech_stack (name) VALUES ('Figma');
INSERT INTO tech_stack (name) VALUES ('Zeplin');
INSERT INTO tech_stack (name) VALUES ('Jest');
INSERT INTO tech_stack (name) VALUES ('Svelte');
