name: CI/CD Pipeline

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    # GitHub-hosted runner(우분투 최신)에서 실행
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) JDK 17 설치 (Temurin 배포판)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3) gradlew 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4) Gradle 빌드 (테스트 제외, 캐시·병렬 빌드)
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --parallel --build-cache -x test

      # 5) Docker Buildx 설치 (필수)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6) Docker Hub 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
          | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 7) Docker 이미지 빌드 & Push
      - name: Build and push Docker image
        run: |
          docker build -t evencrunchy/aibe1-project2-team06-backend:latest .
          docker push evencrunchy/aibe1-project2-team06-backend:latest
